export const products = {
  0: {
    vegetables: [
      "Ail",
      "Betterave",
      "Carotte",
      "Chou",
      "Courge",
      "Crosne",
      "Céleri",
      "Endive",
      "Frisée",
      "Mâche",
      "Navet",
      "Oignon",
      "Panais",
      "Poireau",
      "Pomme de terre",
      "Salsifi",
      "Topinambour",
      "Épinard"
    ],
    fruits: [
      "Citron",
      "Clémentine",
      "Kiwi",
      "Mandarine",
      "Orange",
      "Pamplemousse",
      "Poire",
      "Pomme"
    ]
  },
  1: {
    vegetables: [
      "Ail",
      "Betterave",
      "Carotte",
      "Crosne",
      "Céleri",
      "Endive",
      "Frisée",
      "Mâche",
      "Navet",
      "Oignon",
      "Panais",
      "Poireau",
      "Pomme de terre",
      "Radis",
      "Salsifi",
      "Topinambour",
      "Épinard"
    ],
    fruits: [
      "Citron",
      "Clémentine",
      "Kiwi",
      "Mandarine",
      "Orange",
      "Pamplemousse",
      "Poire",
      "Pomme"
    ]
  },
  2: {
    vegetables: [
      "Ail",
      "Asperge",
      "Betterave",
      "Blette",
      "Carotte",
      "Chou",
      "Chou de Bruxelles",
      "Chou-fleur",
      "Crosne",
      "Céleri",
      "Endive",
      "Frisée",
      "Navet",
      "Oignon",
      "Panais",
      "Poireau",
      "Pomme de terre",
      "Radis",
      "Salsifi",
      "Topinambour",
      "Épinard"
    ],
    fruits: [
      "Citron",
      "Kiwi",
      "Orange",
      "Pamplemousse",
      "Poire",
      "Pomme"
    ]
  },
  3: {
    vegetables: [
      "Ail",
      "Artichaut",
      "Asperge",
      "Betterave",
      "Blette",
      "Carotte",
      "Chou-fleur",
      "Concombre",
      "Céleri",
      "Endive",
      "Frisée",
      "Laitue",
      "Navet",
      "Oignon",
      "Petit pois",
      "Poireau",
      "Pomme de terre",
      "Radis",
      "Épinard"
    ],
    fruits: [
      "Citron",
      "Pamplemousse",
      "Pomme"
    ]
  },
  4: {
    vegetables: [
      "Ail",
      "Artichaut",
      "Asperge",
      "Aubergine",
      "Betterave",
      "Blette",
      "Carotte",
      "Chou-fleur",
      "Concombre",
      "Courgette",
      "Céleri",
      "Laitue",
      "Navet",
      "Oignon",
      "Petit pois",
      "Pomme de terre",
      "Radis",
      "Tomate",
      "Épinard"
    ],
    fruits: [
      "Cerise",
      "Fraise",
      "Pamplemousse",
      "Rhubarbe"
    ]
  },
  5: {
    vegetables: [
      "Ail",
      "Artichaut",
      "Asperge",
      "Aubergine",
      "Betterave",
      "Blette",
      "Brocoli",
      "Carotte",
      "Concombre",
      "Courgette",
      "Céleri",
      "Fenouil",
      "Haricot vert",
      "Laitue",
      "Navet",
      "Oignon",
      "Petit pois",
      "Poivron",
      "Pomme de terre primeur",
      "Radis",
      "Tomate",
      "Épinard"
    ],
    fruits: [
      "Abricot",
      "Cassis",
      "Cerise",
      "Citron",
      "Fraise",
      "Framboise",
      "Groseille",
      "Melon",
      "Pamplemousse",
      "Pastèque",
      "Pomme",
      "Prune",
      "Pêche",
      "Rhubarbe"
    ]
  },
  6: {
    vegetables: [
      "Ail",
      "Artichaut",
      "Asperge",
      "Aubergine",
      "Betterave",
      "Blette",
      "Brocoli",
      "Carotte",
      "Concombre",
      "Courgette",
      "Céleri",
      "Fenouil",
      "Haricot vert",
      "Laitue",
      "Maïs",
      "Oignon",
      "Petit pois",
      "Poivron",
      "Pomme de terre primeur",
      "Radis",
      "Tomate",
      "Épinard"
    ],
    fruits: [
      "Abricot",
      "Cassis",
      "Cerise",
      "Figue",
      "Fraise",
      "Framboise",
      "Féveroles et fèves",
      "Groseille",
      "Melon",
      "Myrtille",
      "Nectarine",
      "Orge d’hiver",
      "Pastèque",
      "Poire",
      "Prune",
      "Pêche",
      "Rhubarbe"
    ]
  },
  7: {
    vegetables: [
      "Ail",
      "Artichaut",
      "Aubergine",
      "Betterave",
      "Blette",
      "Brocoli",
      "Carotte",
      "Concombre",
      "Courge",
      "Courgette",
      "Céleri",
      "Fenouil",
      "Frisée",
      "Haricot vert",
      "Laitue",
      "Maïs",
      "Oignon",
      "Poivron",
      "Pomme de terre primeur",
      "Radis",
      "Tomate",
      "Épinard"
    ],
    fruits: [
      "Abricot",
      "Cassis",
      "Figue",
      "Fraise",
      "Framboise",
      "Féveroles et fèves",
      "Groseille",
      "Melon",
      "Mirabelle",
      "Myrtille",
      "Mûre",
      "Nectarine",
      "Noisette",
      "Pastèque",
      "Poire",
      "Pomme",
      "Prune",
      "Pruneau",
      "Pêche",
      "Raisin"
    ]
  },
  8: {
    vegetables: [
      "Ail",
      "Artichaut",
      "Aubergine",
      "Betterave",
      "Blette",
      "Brocoli",
      "Carotte",
      "Chou",
      "Chou de bruxelles",
      "Chou-fleur",
      "Concombre",
      "Courgette",
      "Céleri",
      "Fenouil",
      "Frisée",
      "Haricot vert",
      "Laitue",
      "Maïs",
      "Oignon",
      "Panais",
      "Poireau",
      "Poivron",
      "Pomme de terre",
      "Potiron",
      "Radis",
      "Tomate",
      "Épinard"
    ],
    fruits: [
      "Coing",
      "Figue",
      "Melon",
      "Mirabelle",
      "Myrtille",
      "Mûre",
      "Noisette",
      "Noix",
      "Pastèque",
      "Poire",
      "Pomme",
      "Prune",
      "Pruneau",
      "Pêche",
      "Raisin"
    ]
  },
  9: {
    vegetables: [
      "Ail",
      "Aubergine",
      "Betterave",
      "Blette",
      "Brocoli",
      "Carotte",
      "Chou",
      "Chou de Bruxelles",
      "Chou-fleur",
      "Concombre",
      "Courge",
      "Courgette",
      "Céleri",
      "Endive",
      "Fenouil",
      "Frisée",
      "Haricot vert",
      "Laitue",
      "Maïs",
      "Navet",
      "Oignon",
      "Panais",
      "Poireau",
      "Pomme de terre",
      "Potiron",
      "Radis",
      "Rutabaga",
      "Salsifis",
      "Tomate",
      "Topinambour",
      "Épinard"
    ],
    fruits: [
      "Châtaigne",
      "Citron",
      "Coing",
      "Figue",
      "Framboise",
      "Myrtille",
      "Noisette",
      "Noix",
      "Poire",
      "Pomme",
      "Raisin"
    ]
  },
  10: {
    vegetables: [
      "Ail",
      "Betterave",
      "Brocoli",
      "Cardon",
      "Carotte",
      "Chou",
      "Chou-fleur",
      "Citrouille",
      "Courge",
      "Crosne",
      "Céleri",
      "Endive",
      "Fenouil",
      "Épinard",
      "Mâche",
      "Navet",
      "Oignon",
      "Panais",
      "Poireau",
      "Pomme de terre",
      "Potiron",
      "Radis"
    ],
    fruits: [
      "Châtaigne",
      "Citron",
      "Clémentine",
      "Coing",
      "Kiwi",
      "Mandarine",
      "Orange",
      "Poire",
      "Pomme"
    ]
  },
  11: {
    vegetables: [
      "Ail",
      "Betterave",
      "Carotte",
      "Chou",
      "Chou de Bruxelles",
      "Courge",
      "Crosne",
      "Céleri",
      "Endive",
      "Frisée",
      "Mâche",
      "Navet",
      "Oignon",
      "Panais",
      "Poireau",
      "Pomme de terre",
      "Potiron",
      "Radis",
      "Rutabaga",
      "Salsifi",
      "Topinambour",
      "Épinard"
    ],
    fruits: [
      "Châtaigne",
      "Citron",
      "Clémentine",
      "Féveroles et fèves",
      "Kiwi",
      "Mandarine",
      "Orange",
      "Poire",
      "Pomme"
    ]
  },
}

export const fullMonthLabel = {
  0: 'janvier',
  1: 'février',
  2: 'mars',
  3: 'avril',
  4: 'mai',
  5: 'juin',
  6: 'juillet',
  7: 'août',
  8: 'septembre',
  9: 'octobre',
  10: 'novembre',
  11: 'décembre'
}
